### ISSUE TITLE
can't control dragged div

### ISSUE THREAD

**Issue by Zulfia73** [JakeSidSmith/react-reorder#84] opened 2017-06-21 07:30 UTC
![image](https://user-images.githubusercontent.com/6208460/27372205-72af6b80-566c-11e7-85fb-f558c54c9718.png)

I I can't understand, how controlling dragged element

**Comment by JakeSidSmith** [comment] 2017-06-21 09:23
What version are you using?
I looks like you have somehow overridden the position styles.
The element should have these:

```js
var draggedStyle = {
  position: 'fixed',
  top: rect.top,
  left: rect.left,
  width: rect.width,
  height: rect.height
};
```

Check if there is something with `!important` that is affecting it.

**Comment by Zulfia73** [comment] 2017-06-21 09:35
file.js => 
        var draggedStyle = {
          position: 'fixed',
          top: rect.top,
          left: rect.left,
          width: rect.width,
          height: rect.height
        };

listClass={classes.flexContainer} =>  
.flexContainer {
	display: flex;
	flex-wrap: wrap;
	width: 100%;
	position: relative;

**Comment by Zulfia73** [comment] 2017-06-21 09:36
my class => 
.dragged {
  background-color: #EEE ;
  transform: scale(0.98, 0.98) ;
  opacity: 0.7 ;
}

**Comment by JakeSidSmith** [comment] 2017-06-21 09:38
Looks like that `position: relative;` is what could be doing it. Try targetting your dragged class, which will be `dragged` by default.

```css
.dragged {
  position: fixed;
}
```

**Comment by Zulfia73** [comment] 2017-06-21 09:43
@JakeSidSmith 
![default](https://user-images.githubusercontent.com/6208460/27377959-1856b04a-567f-11e7-9dc2-e62adf3ab739.png)

On the basis what, are you made calculations for dragged?

**Comment by JakeSidSmith** [comment] 2017-06-21 09:56
`element.getBoundingClientRect()` which gives you its exact position on the page.

You must have some other style overriding it. I've never seen something like this before.

Have a look in the styles panel down the right of the inspector.

**Comment by Zulfia73** [comment] 2017-06-21 10:39
@JakeSidSmith Strange, but the problem is only with the parameter left

**Comment by JakeSidSmith** [comment] 2017-06-21 10:42
It could be something do do with being `display: flex;`. I haven't used flexbox with react-reorder at all.

It's hard to say what the solution is without having a look at the app / code.

**Comment by Zulfia73** [comment] 2017-06-21 10:46
@JakeSidSmith nope, problem not in flex

**Comment by Zulfia73** [comment] 2017-06-21 10:48
getBoundingClientRect retutn wrong left parametr
ClientRect {top: 220.5, right: 990.53125, bottom: 247.5, left: 854.53125, width: 136…}

**Comment by Zulfia73** [comment] 2017-06-21 11:22
@IakeSidSmith ,  
![default](https://user-images.githubusercontent.com/6208460/27381852-11d0e30e-568d-11e7-9439-2592b3249c1b.png)
find problem

**Comment by giricgoyal** [comment] 2018-04-05 03:42
I am having the same issue. I have the "Reorder" component in a Modal though. I don't think that should make a difference. The values `getBoundingClientRect` is returning seems to fine. Event the `.dragged` element has `position: fixed`. Still the element seems to be sticking at the right edge of the viewport and a few pixel below the mouse position.

**Comment by giricgoyal** [comment] 2018-04-05 03:58
So after digging in to what was causing this, the modal's (or parent's) transform property causes this bug to creep up.

**Comment by giricgoyal** [comment] 2018-04-05 04:21
@Zulfia73 : You might want to consider a different approach when you are using `transform` property on the parent.

**Comment by JakeSidSmith** [comment] 2018-04-05 09:08
Ah, @giricgoyal good catch. I ran into issues caused by transform just a week or so ago (but not with react-reorder). That is quite possibly the cause of this issue.

Frustrating that certain properties cause `position: fixed;` to behave differently.

Unfortunately if I were to use `position: absolute;` and position the items relative to their parent they would end up having overflow issues (being hidden outside, or causing the parent to scroll).

**Comment by giricgoyal** [comment] 2018-04-05 09:12
@JakeSidSmith : Unfortunately, the only solution I have found so far is to refactor the parent to not use `transform` properties. Would love to know whenever you have a different solution.

**Comment by Pickra** [comment] 2018-04-16 21:34
Thanks for the no `transform` suggestion @giricgoyal, totally saved me

**Comment by JakeSidSmith** [comment] 2021-03-13 12:12
I don't think there's another way I can resolve this besides suggesting the `transform` is removed (not without completely changing how this lib works anyway e.g. rendering dragged items outside of the reorder component using portals).

I'll consider this for a future version. Closing for now.

**Closed by JakeSidSmith** 2021-03-13 12:12 UTC
